### ISSUE TITLE
Exclude (uncovered) Interfaces from XML Report

### ISSUE THREAD

**Issue by delsner** [cqse/teamscale-jacoco-agent#272]
Hi, thanks for the great wrapper around JaCoCo.

I'm using the agent in normal mode and inside the generated XMLs I also see Sourcefile elements for Interfaces.
These elements are naturally empty; they (typically) don't include any covered lines/branches (e.g., `<sourcefile name="IFoo.java"/>`).
However, (some?) post-processing tools, e.g. [`grcov`](https://github.com/mozilla/grcov), treat such elements as invalid (see [here](https://github.com/mozilla/grcov/blob/2dac8cf9ed5d1b4e8ae5bef7b9a82f8ba18e2389/src/parser.rs#L754)) and fail parsing the entire XML file.
I would've expected that the option `ignore-uncovered-classes=true` not only excludes uncovered classes, but also interfaces without coverable code. 
Do you have any other suggestions how to deal with the problem of empty Sourcefile elements for Interfaces?

Thanks!

**Comment by DreierF** [comment]
Hi Daniel,

Thanks for reporting the issue!
I would not consider an empty `<sourcefile ... />` node as invalid (JaCoCo produces the same output for those and its output basically is the specification of the format), but I agree that `ignore-uncovered-classes=true` should also remove empty interface elements.
I guess the problem is [here](https://github.com/cqse/teamscale-jacoco-agent/blob/9552c01d3646bfbc9cec17734e90927171a8f446/report-generator/src/main/java/com/teamscale/report/jacoco/TeamscaleCoverageBuilder.java#L50) and we should also abort the traversal when the status is `ICounter.EMPTY`.

I have created an internal ticket on our side to look into it, but we are also open to PRs :)

**Comment by delsner** [comment]
@DreierF thanks for your response. I've patched this with a simple Python script as you're correct, this is not invalid according to JaCoCo. I'm leaving it here in case somebody finds it helpful:

```python
import re
from pathlib import Path

# remove all empty sourcefile elements from JaCoCo reports
for xml_path in Path('coverage').glob('**/*.xml'):
    content = xml_path.read_text()
    content = re.sub(r'<sourcefile name=\\"[^>]+?\\"/>', '', content, 0, re.MULTILINE)
    xml_path.write_text(content)
```
